# Generated by Django 4.0.4 on 2022-06-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrevistas', '0008_alter_entrevistasmodel_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Comentario', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrevistas.entrevistasmodel')),
            ],
        ),
    ]
