# Generated by Django 4.0.4 on 2022-06-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Localidad', models.CharField(max_length=100)),
                ('Entrevistado', models.CharField(max_length=100)),
                ('Anecdota', models.TextField()),
                ('Corresponsal', models.CharField(max_length=100)),
                ('Finalizado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
