# Generated by Django 4.0.4 on 2022-06-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrevistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrevistaModel',
            new_name='EntrevistasModel',
        ),
    ]
