# Generated by Django 4.0.4 on 2022-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrevistas', '0002_rename_entrevistamodel_entrevistasmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('Ultima_modificacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
