# Generated by Django 4.0.4 on 2022-06-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrevistas', '0003_lectoresmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectoresModel',
        ),
    ]
