# Generated by Django 4.0.4 on 2022-06-17 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Entrevistas', '0004_delete_lectoresmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistasmodel',
            name='Corresponsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
