# Generated by Django 4.0.4 on 2022-06-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrevistas', '0005_alter_entrevistasmodel_corresponsal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistasmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos'),
        ),
    ]
