# Generated by Django 4.0.4 on 2022-06-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrevistas', '0006_entrevistasmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrevistasmodel',
            old_name='image',
            new_name='Imagen',
        ),
    ]
